name: utility_bill_logger
description: A Flutter mobile app for tracking utility bill consumption
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.0.0

  # HTTP Client
  http: ^1.1.0

  # Local Storage
  shared_preferences: ^2.0.15

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.2.0

  # Date & Time
  intl: ^0.20.2

  # Utilities
  uuid: ^4.2.1

  # Charting
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

