name: utility_bill_logger
description: "A utility bill logging application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # HTTP Client
  http: ^1.1.0

  # Local Storage
  shared_preferences: ^2.2.2

  # UI Components
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.2.0

  # Date & Time
  intl: ^0.20.2

  # Utilities
  uuid: ^4.2.1

  # Charting
  fl_chart: ^0.66.0

  # Launcher Icons
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#2563EB"
    theme_color: "#2563EB"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"

